//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHBatch
    {
        public ACHBatch()
        {
            this.ACHBatchDetails = new HashSet<ACHBatchDetails>();
        }
    
        public int ACHBatchID { get; set; }
        public System.DateTime BatchDate { get; set; }
        public int BatchNumber { get; set; }
        public string ACHGroupID { get; set; }
        public bool CreditsCreated { get; set; }
        public Nullable<System.DateTime> ACHPullDate { get; set; }
        public string StateFilter { get; set; }
        public byte[] upsize_ts { get; set; }
        public string BatchType { get; set; }
        public bool FileCreated { get; set; }
        public Nullable<System.DateTime> FileCreatedOn { get; set; }
        public string FileCreatedBy { get; set; }
        public Nullable<int> DepositBankAccountID { get; set; }
        public Nullable<int> ACHBatchGroupID { get; set; }
        public Nullable<System.DateTime> ProcessACHDate { get; set; }
        public Nullable<System.DateTime> ScheduleACHPullDate { get; set; }
        public Nullable<int> DaysBeforeACHPullDate { get; set; }
        public Nullable<System.DateTime> OverrideACHPullDate { get; set; }
        public string FileName { get; set; }
        public bool IsSECCodesEnabled { get; set; }
        public string FileIDModifier { get; set; }
        public Nullable<System.DateTime> PaymentProcessor_SubmitDate { get; set; }
        public Nullable<int> MasterCreditorID { get; set; }
        public Nullable<int> MasterDebtorID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual ACHBatchGroup ACHBatchGroup { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Creditors Creditors { get; set; }
        public virtual ICollection<ACHBatchDetails> ACHBatchDetails { get; set; }
    }
}
