//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHBankAccounts
    {
        public ACHBankAccounts()
        {
            this.ACHBankAccounts1 = new HashSet<ACHBankAccounts>();
            this.ACHBatchDetails = new HashSet<ACHBatchDetails>();
        }
    
        public int ACHBankAccountID { get; set; }
        public int ClientID { get; set; }
        public string BankName { get; set; }
        public string ABA { get; set; }
        public string AccType { get; set; }
        public string BankAccountNumber { get; set; }
        public string ACHNote { get; set; }
        public string AccountFirstName { get; set; }
        public string AccountLastName { get; set; }
        public bool DefaultBankAccount { get; set; }
        public string BankAccountName { get; set; }
        public byte[] upsize_ts { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public Nullable<System.DateTime> StatusSentDate { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public bool LinkToProcessingAccount { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress2 { get; set; }
        public Nullable<System.DateTime> PrenoteSent { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public Nullable<int> LeadACHBankAccountID { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
        public string PIN { get; set; }
        public Nullable<int> FundingAccountType { get; set; }
        public Nullable<long> StartCheck { get; set; }
        public bool UsePhonePay { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public string OperatorStamp { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<int> ProcessingPolicyGroupID { get; set; }
        public Nullable<bool> GCSExported { get; set; }
        public string EnteredByWebUserName { get; set; }
        public string AccountCompanyName { get; set; }
        public bool IsEmergencyFund { get; set; }
        public Nullable<int> LinkedToMasterACHBankAccountID { get; set; }
        public string BankAccountNumber_Masked { get; set; }
        public byte[] UserID_Secret { get; set; }
        public byte[] Password_Secret { get; set; }
        public Nullable<decimal> ACHBankAccountBalance { get; set; }
        public Nullable<System.DateTime> ACHBankAccountBalanceVerifiedOn { get; set; }
        public string ACHBankAccountBalanceVerifiedBy { get; set; }
        public Nullable<int> FinancialInstitutionID { get; set; }
        public string M2_CardHolderID { get; set; }
        public Nullable<decimal> M2_AvailableBalance { get; set; }
        public string M2_Status { get; set; }
        public bool M2_BankInfo_NeedsUpdate { get; set; }
        public short M2_BIN2_Counter_CALCULATED { get; set; }
        public short M2_BIN4_Counter_CALCULATED { get; set; }
        public string PaymentProcessor_TransactionRefID { get; set; }
        public bool PaymentProcessor_NeedsUpdate { get; set; }
        public Nullable<int> YodleeItemAccountID { get; set; }
    
        public virtual ICollection<ACHBankAccounts> ACHBankAccounts1 { get; set; }
        public virtual ACHBankAccounts ACHBankAccounts2 { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ICollection<ACHBatchDetails> ACHBatchDetails { get; set; }
    }
}
