//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHBatchGroup
    {
        public ACHBatchGroup()
        {
            this.ACHBatch = new HashSet<ACHBatch>();
        }
    
        public int ACHBatchGroupID { get; set; }
        public Nullable<System.DateTime> StartDateFilter { get; set; }
        public Nullable<System.DateTime> EndDateFilter { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string BatchType { get; set; }
    
        public virtual ICollection<ACHBatch> ACHBatch { get; set; }
    }
}
