//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHBatchDetails
    {
        public ACHBatchDetails()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int ACHBatchDetailID { get; set; }
        public int ACHBatchID { get; set; }
        public int ClientID { get; set; }
        public decimal Amount { get; set; }
        public bool Selected { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> ACHBankAccountID { get; set; }
        public Nullable<int> ACHUserEntriesID { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<int> ClientACHGroupID { get; set; }
        public Nullable<decimal> GCSDebitID { get; set; }
        public string StandardEntryClassCode { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> DateCredited { get; set; }
        public Nullable<System.DateTime> HoldUntil { get; set; }
        public bool SentToPaymentProcessor { get; set; }
        public string M2_TransactionID { get; set; }
        public string PaymentProcessor_TransactionRefID { get; set; }
    
        public virtual ACHBankAccounts ACHBankAccounts { get; set; }
        public virtual ACHBatch ACHBatch { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
