//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHGroups
    {
        public string ACHGroupID { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public string Period { get; set; }
        public Nullable<short> DraftDay { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public string WeekDay { get; set; }
        public bool Show { get; set; }
        public Nullable<int> CreditCardBankAccountID { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
        public virtual BankAccounts BankAccounts1 { get; set; }
    }
}
