//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int BankID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> EntryAmount { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public bool EntryCleared { get; set; }
        public Nullable<System.DateTime> DateEntryCleared { get; set; }
        public int BankAccountID { get; set; }
        public string OperatorStamp { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public bool Reconciled { get; set; }
        public Nullable<System.DateTime> ReconciledDate { get; set; }
        public bool AutomaticEntry { get; set; }
        public Nullable<int> BankRecHistoryID { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<int> OriginatingFromNSFReceiptID { get; set; }
        public string EnteredBy { get; set; }
    
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
