//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public BankAccounts()
        {
            this.ACHGroups = new HashSet<ACHGroups>();
            this.Creditors = new HashSet<Creditors>();
            this.Payments = new HashSet<Payments>();
            this.ACHGroups1 = new HashSet<ACHGroups>();
        }
    
        public int BankAccountID { get; set; }
        public string Name { get; set; }
        public string BankName { get; set; }
        public string ABA { get; set; }
        public string AccountNumber { get; set; }
        public string ImmediateOrigin { get; set; }
        public bool EFT { get; set; }
        public string OriginatorID { get; set; }
        public string RPSOutputFile { get; set; }
        public string RPSTestFile { get; set; }
        public string RPSPhoneNumber { get; set; }
        public string RPSCompanyName { get; set; }
        public bool ACH { get; set; }
        public string ACHOutputFile { get; set; }
        public string ACHABA { get; set; }
        public string ACHAccountNumber { get; set; }
        public string ACHImmediateOrigin { get; set; }
        public string ACHCompanyID { get; set; }
        public string DMPOutputFile { get; set; }
        public string DiscretionaryData { get; set; }
        public string DS { get; set; }
        public string RPSAnalysisFile { get; set; }
        public string ACHBalancedABA { get; set; }
        public bool SkipBalancingRecord { get; set; }
        public bool Active { get; set; }
        public Nullable<int> LinkBankAccountID { get; set; }
        public string VisaOriginatorID { get; set; }
        public string VisaDMPOutputFile { get; set; }
        public string PaperCheckFile { get; set; }
        public string ClientIdentifier { get; set; }
        public bool CreateCheckFile { get; set; }
        public string PaperCheckFileTest { get; set; }
        public string ACHPrenoteOutputFile { get; set; }
        public byte[] upsize_ts { get; set; }
        public string OriginatingDFI { get; set; }
        public bool CFG { get; set; }
        public string TDDataCentre { get; set; }
        public string TDAcctForReturns { get; set; }
        public string TDInstForReturns { get; set; }
        public string CPABankAccountID { get; set; }
        public bool IsVirtual { get; set; }
        public bool IsOperating { get; set; }
        public string CurrencyCodeIdentifier { get; set; }
        public int ACHLastFileNumber { get; set; }
        public bool IsBillingDeposit { get; set; }
        public bool IsSECCodesEnabled { get; set; }
        public Nullable<int> DaysBeforeACHPullDate { get; set; }
        public string CheckFileFormat { get; set; }
        public string ACHCompanyEntryDescription { get; set; }
        public Nullable<int> CCType { get; set; }
        public string M2_CardHolderID { get; set; }
        public string M2_2BIN_PaperChecks { get; set; }
        public string M2_2BIN_PhoneChecks { get; set; }
        public string M2_7BIN_Agency { get; set; }
        public int M2_BIN2_Counter_CALCULATED { get; set; }
        public string M2_CardHolderID_BIN2 { get; set; }
        public bool M2_BankInfo_NeedsUpdate { get; set; }
        public bool UseForBillPay { get; set; }
        public string PaymentProcessor_TransactionRefID { get; set; }
        public string OverwriteACHFormat { get; set; }
    
        public virtual ICollection<ACHGroups> ACHGroups { get; set; }
        public virtual ICollection<Creditors> Creditors { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<ACHGroups> ACHGroups1 { get; set; }
    }
}
