//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        public int CheckID { get; set; }
        public int BankAccountID { get; set; }
        public Nullable<int> CreditorID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool Cleared { get; set; }
        public bool Voided { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateCleared { get; set; }
        public Nullable<int> VoidReason { get; set; }
        public Nullable<int> VoidNewCreditorID { get; set; }
        public string OperatorStamp { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public bool Reconciled { get; set; }
        public Nullable<System.DateTime> ReconciledDate { get; set; }
        public string Payee { get; set; }
        public Nullable<int> SalesForceID { get; set; }
        public string CheckType { get; set; }
        public Nullable<int> CheckRunID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> BankRecHistoryID { get; set; }
        public string QBID { get; set; }
        public byte[] upsize_ts { get; set; }
        public string VoidDescription { get; set; }
        public int NumberOfEntries_CALCULATED { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<decimal> FSAmount_CALCULATED { get; set; }
        public string PaymentProcessor_TranStatus { get; set; }
        public string PaymentProcessor_StopPayOnCheckStatus { get; set; }
        public Nullable<System.DateTime> PaymentProcessor_CSLastUpdatedTime { get; set; }
    
        public virtual CheckRun CheckRun { get; set; }
        public virtual Creditors Creditors { get; set; }
    }
}
