//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCred
    {
        public ClientCred()
        {
            this.ClientCred1 = new HashSet<ClientCred>();
        }
    
        public int ClientCredID { get; set; }
        public int ClientID { get; set; }
        public int CreditorID { get; set; }
        public string CreditorAlias { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<System.DateTime> LastPay { get; set; }
        public Nullable<System.DateTime> LastIncr { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> OrigDebt { get; set; }
        public Nullable<decimal> DefMonthlyPayment { get; set; }
        public Nullable<decimal> PrevPay1 { get; set; }
        public Nullable<decimal> OrigMonthly { get; set; }
        public Nullable<decimal> BegDebt { get; set; }
        public Nullable<decimal> InitialAPR { get; set; }
        public Nullable<decimal> ReducedAPR { get; set; }
        public bool Commission { get; set; }
        public bool Closed { get; set; }
        public Nullable<int> XCreditorID { get; set; }
        public string XAccountNumber { get; set; }
        public bool OverrideFS { get; set; }
        public Nullable<decimal> NewFS { get; set; }
        public string OperatorStamp { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<System.DateTime> OriginalDueDate { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<decimal> PmtRequested { get; set; }
        public Nullable<System.DateTime> PmtRequestedDate { get; set; }
        public Nullable<decimal> UpdatedBalance { get; set; }
        public Nullable<System.DateTime> UpdatedBalanceDate { get; set; }
        public Nullable<decimal> ConfirmedMonthly { get; set; }
        public Nullable<System.DateTime> ConfirmedMonthlyDate { get; set; }
        public Nullable<decimal> ConfirmedBalance { get; set; }
        public Nullable<System.DateTime> ConfirmedBalanceDate { get; set; }
        public Nullable<decimal> PaidToDate_CALCULATED { get; set; }
        public string AddedBy { get; set; }
        public string UserDefined1 { get; set; }
        public string UserDefined2 { get; set; }
        public Nullable<decimal> PmtRequestedCreditor { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public Nullable<decimal> OldPayment { get; set; }
        public decimal AccumulateAmount { get; set; }
        public bool BillPay { get; set; }
        public Nullable<decimal> BillPayAmount { get; set; }
        public Nullable<int> ACHBankAccountID { get; set; }
        public Nullable<System.DateTime> BillPayStartDate { get; set; }
        public string BillPayPeriodType { get; set; }
        public Nullable<int> BillPayPeriodCount { get; set; }
        public Nullable<System.DateTime> BillPayNextDate { get; set; }
        public Nullable<System.DateTime> FirstProposalSent { get; set; }
        public Nullable<int> OverridePayPriority { get; set; }
        public Nullable<int> XClientCredID { get; set; }
        public bool SecuredDebt { get; set; }
        public Nullable<decimal> LoanOriginalValue { get; set; }
        public Nullable<short> LoanTerm { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string InternetCreditorName { get; set; }
        public Nullable<System.DateTime> BalanceVerifiedOn { get; set; }
        public bool CurrentDefModifyManually { get; set; }
        public Nullable<decimal> MinimumAcceptedByCreditor { get; set; }
        public string DelinquencyStatus { get; set; }
        public Nullable<short> AccountDueDay { get; set; }
        public string SSNApplicant { get; set; }
        public bool CommissionCalculated { get; set; }
        public Nullable<int> CommissionBatchID { get; set; }
        public Nullable<System.DateTime> NegotiatedDate { get; set; }
        public Nullable<int> FeeClientCredID { get; set; }
        public Nullable<decimal> SettlementPercentage { get; set; }
        public Nullable<decimal> BalanceAtTimeOfSettlement { get; set; }
        public Nullable<System.DateTime> SettlementApprovedOn { get; set; }
        public bool Priority { get; set; }
        public bool Lock { get; set; }
        public bool IsTransferredAccount { get; set; }
        public bool DND { get; set; }
        public Nullable<System.DateTime> LastProposalSent { get; set; }
        public Nullable<int> OrigCreditorID { get; set; }
        public string CreditorPaymentType { get; set; }
        public Nullable<decimal> OverrideEstimatedSettlementPercentage { get; set; }
        public string NegotiatorUserID { get; set; }
        public bool SettlementFeeBasedOnOrigBalance { get; set; }
        public bool UseVirtual { get; set; }
        public bool PreBankruptcy { get; set; }
        public bool LessThanFull { get; set; }
        public Nullable<decimal> EstimatedSettlementAmount { get; set; }
        public bool HoldProposal { get; set; }
        public bool HoldProposalUntilFirstReceipt { get; set; }
        public string AccountNumberStripped { get; set; }
        public bool CRTransUnion { get; set; }
        public bool CRExperian { get; set; }
        public bool CREquifax { get; set; }
        public Nullable<int> CRTransUnionIssueID { get; set; }
        public Nullable<int> CRExperianIssueID { get; set; }
        public Nullable<int> CREquifaxIssueID { get; set; }
        public Nullable<int> CoAppID { get; set; }
        public Nullable<int> LeadClientCredID { get; set; }
        public Nullable<int> DefaultCreditorID { get; set; }
        public bool LockedAfterRecordPayment { get; set; }
        public Nullable<decimal> EstimatedSettlementFees { get; set; }
        public Nullable<int> CreditorContactID { get; set; }
        public string AccountName_CALCULATED { get; set; }
        public bool JointAccount { get; set; }
        public bool StatementReceived { get; set; }
        public bool MOD10_CALCULATED { get; set; }
        public Nullable<decimal> MinimumPayment_CALCULATED { get; set; }
        public int RPPS_AutoResend_Counter_CALCULATED { get; set; }
        public Nullable<int> ContactScheduleID { get; set; }
        public bool DNDDirty { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public bool CallToAction { get; set; }
        public bool Hardship { get; set; }
        public Nullable<int> CollectionPlanID { get; set; }
        public Nullable<bool> OverrideInternalFee { get; set; }
        public Nullable<decimal> NewInternalFeePercentage { get; set; }
        public Nullable<decimal> TempPayment { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<decimal> DefaultFee { get; set; }
        public Nullable<decimal> TempFeeAmount { get; set; }
        public Nullable<decimal> TempExternalFeeAmount { get; set; }
        public bool ClientPaymentEntrySelection { get; set; }
        public Nullable<decimal> TempDistribution { get; set; }
        public Nullable<decimal> TempExternalDistribution { get; set; }
        public Nullable<decimal> TempMaxFeeAmount { get; set; }
        public string EnteredByWebUserName { get; set; }
        public string DebtType { get; set; }
        public Nullable<bool> ReportToCreditBureaus { get; set; }
        public bool Metro2Closed { get; set; }
        public Nullable<int> Metro2LastExportID { get; set; }
        public string CreditReportConsumerTransactionCode { get; set; }
        public string CreditReportAccountStatusCode { get; set; }
        public string CreditReportECOACode { get; set; }
        public string CreditReportComplianceCode { get; set; }
        public string CreditReportPaymentHistory { get; set; }
        public string CreditReportPaymentRatingCode { get; set; }
        public string CreditReportSpecialComment { get; set; }
        public Nullable<System.DateTime> LastCreditListedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.DateTime> FirstDelinquencyDate { get; set; }
        public Nullable<decimal> PastDueAmount { get; set; }
        public Nullable<int> ImportDataLogID { get; set; }
        public Nullable<int> CollectionCampaignID { get; set; }
        public Nullable<int> OrigCreditorID_CALCULATED { get; set; }
        public Nullable<int> OverrideSalesmanID { get; set; }
        public bool FullBudgetDisclosure_CALCULATED { get; set; }
        public bool FullBudgetCreditors_CALCULATED { get; set; }
        public bool SendProposalsByFax_CALCULATED { get; set; }
        public bool UseRPPSProposals_CALCULATED { get; set; }
        public string AccountNumber_Masked { get; set; }
        public byte[] AccountNumber_Encrypted { get; set; }
        public Nullable<int> RetainerFeePSDID { get; set; }
        public string SSNApplicant_Masked { get; set; }
        public Nullable<int> DefaultProgramScheduleSetupID { get; set; }
        public Nullable<int> XClientID { get; set; }
        public Nullable<decimal> ReducedAPRBasedOnFormula_CALCULATED { get; set; }
        public Nullable<System.DateTime> FirstProposalCreated { get; set; }
        public Nullable<int> AccountTerm { get; set; }
        public Nullable<decimal> UnpaidInterest { get; set; }
        public Nullable<decimal> InterestPaidToDate_CALCULATED { get; set; }
        public int NoOffers_CALCULATED { get; set; }
        public string UserDefined3 { get; set; }
        public bool PastDueAccount { get; set; }
        public Nullable<System.DateTime> DateAccountCheckedAsPastDue { get; set; }
        public Nullable<int> YodleeStatus { get; set; }
        public Nullable<int> YodleeTransactionStatus { get; set; }
        public Nullable<int> YodleeItemID { get; set; }
        public Nullable<int> YodleeItemAccountID { get; set; }
        public Nullable<System.DateTime> YodleeLastTransactionRequest { get; set; }
        public Nullable<int> YodleeContentServiceID { get; set; }
        public int AccountOrdinalNumber_CALCULATED { get; set; }
        public short BillPayAmountOption { get; set; }
        public short BillPaySourceOption { get; set; }
        public Nullable<System.DateTime> BillPayAmountVerifiedOn { get; set; }
        public string BillPayAmountVerifiedBy { get; set; }
        public bool ProposalSentPriorToConversion { get; set; }
        public Nullable<int> BudgetCategoryID { get; set; }
        public Nullable<int> BillPaymentType { get; set; }
        public bool ExcludeFromBudgetAnalysis { get; set; }
        public bool BudgetUseYodleeTransactions { get; set; }
        public Nullable<int> PaymentTermID { get; set; }
        public Nullable<System.DateTime> FinancialDiscount_DueDate { get; set; }
        public Nullable<decimal> FinanciaDiscount_AmountToPay { get; set; }
        public Nullable<decimal> PrincipalBalance_CALCULATED { get; set; }
        public Nullable<int> LastBalanceChangeID_CALCULATED { get; set; }
        public string SLS_LoanType { get; set; }
        public Nullable<int> ProcedureID { get; set; }
        public Nullable<int> ItemUnits { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<int> PresetID { get; set; }
        public Nullable<System.DateTime> SuspensionStartDate { get; set; }
        public Nullable<System.DateTime> SuspensionEndDate { get; set; }
        public string SuspensionReason { get; set; }
        public string OverpaymentReason { get; set; }
        public Nullable<int> OriginalMasterClientID { get; set; }
    
        public virtual ICollection<ClientCred> ClientCred1 { get; set; }
        public virtual ClientCred ClientCred2 { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual CoApps CoApps { get; set; }
        public virtual Creditors Creditors { get; set; }
        public virtual Clients Clients1 { get; set; }
    }
}
