//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.ACHBankAccounts = new HashSet<ACHBankAccounts>();
            this.ACHBatch = new HashSet<ACHBatch>();
            this.ACHBatchDetails = new HashSet<ACHBatchDetails>();
            this.ClientCred = new HashSet<ClientCred>();
            this.ClientCred1 = new HashSet<ClientCred>();
            this.Clients1 = new HashSet<Clients>();
            this.CoApps1 = new HashSet<CoApps>();
            this.Payments = new HashSet<Payments>();
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int ClientID { get; set; }
        public string SSN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Results { get; set; }
        public string Referral { get; set; }
        public string Counselor { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<short> PaymentDay { get; set; }
        public Nullable<System.DateTime> FDisDate { get; set; }
        public string WholeName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string OtherPhone { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<decimal> LastPaymentAmount { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public string CloseReason { get; set; }
        public string Note { get; set; }
        public string StatementNote { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> EditableUntil { get; set; }
        public Nullable<int> SalesmanID { get; set; }
        public Nullable<int> SalesmanType { get; set; }
        public string SalesmanUID { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<short> EmailStatus { get; set; }
        public bool UseACH { get; set; }
        public string Language { get; set; }
        public bool TempClient { get; set; }
        public Nullable<System.DateTime> MonthlyStatementPrinted { get; set; }
        public Nullable<System.DateTime> MonthlyStatementSDATE { get; set; }
        public Nullable<System.DateTime> MonthlyStatementEDATE { get; set; }
        public bool FirstPmtRcvd { get; set; }
        public string OperatorStamp { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public byte[] upsize_ts { get; set; }
        public string ClientStatus { get; set; }
        public Nullable<int> LeadClientID { get; set; }
        public string UserDefined1 { get; set; }
        public string UserDefined2 { get; set; }
        public string UserDefined3 { get; set; }
        public string UserDefined4 { get; set; }
        public string UserDefined5 { get; set; }
        public Nullable<System.DateTime> StatusChangedOn { get; set; }
        public string CurrentACHGroupID { get; set; }
        public string ACHNote { get; set; }
        public string TasksLockedByUserID { get; set; }
        public Nullable<bool> CallBack { get; set; }
        public string EnteredBy { get; set; }
        public decimal SetServiceFee { get; set; }
        public Nullable<int> DefaultBankAccount { get; set; }
        public bool DND { get; set; }
        public string UserDefined6 { get; set; }
        public Nullable<int> AdvertisingID { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> MonthlyServiceFeeCalculatedOn { get; set; }
        public Nullable<long> CompletionBonusBatchID { get; set; }
        public string ClientAdminStatus { get; set; }
        public string AppointmentSpecialist { get; set; }
        public string AccountManager { get; set; }
        public string Salutation { get; set; }
        public string PreferredCommunicationMethod { get; set; }
        public string WorkPhoneTime { get; set; }
        public string HomePhoneTime { get; set; }
        public string MobilePhoneTime { get; set; }
        public string WorkPhoneType { get; set; }
        public string HomePhoneType { get; set; }
        public string MobilePhoneType { get; set; }
        public Nullable<System.DateTime> FileReceivedOn { get; set; }
        public Nullable<System.DateTime> ProgramFeeDueDate { get; set; }
        public Nullable<int> ProgramLength { get; set; }
        public Nullable<int> ProgramScheduleID { get; set; }
        public bool Address1CommunicationPreferred { get; set; }
        public bool Address1CommunicationDoNotUse { get; set; }
        public bool HomePhoneCommunicationPreferred { get; set; }
        public bool HomePhoneCommunicationDoNotUse { get; set; }
        public bool WorkPhoneCommunicationPreferred { get; set; }
        public bool WorkPhoneCommunicationDoNotUse { get; set; }
        public bool OtherPhoneCommunicationPreferred { get; set; }
        public bool OtherPhoneCommunicationDoNotUse { get; set; }
        public bool EmailCommunicationPreferred { get; set; }
        public bool EmailCommunicationDoNotUse { get; set; }
        public bool FaxCommunicationPreferred { get; set; }
        public bool FaxCommunicationDoNotUse { get; set; }
        public bool MobileCommunicationPreferred { get; set; }
        public bool MobileCommunicationDoNotUse { get; set; }
        public string HomePhoneStripped { get; set; }
        public string WorkPhoneStripped { get; set; }
        public string OtherPhoneStripped { get; set; }
        public string FAXStripped { get; set; }
        public decimal AmountDue_CALCULATED { get; set; }
        public string MobilePhoneStripped { get; set; }
        public string UserDefined7 { get; set; }
        public string FeeStatus { get; set; }
        public Nullable<System.DateTime> LastTimeJobAddedSchedulePoints { get; set; }
        public decimal UnusedUnallocatedAmount_CALCULATED { get; set; }
        public decimal UnusedRealAccumulatedAmount_CALCULATED { get; set; }
        public decimal UnusedVirtualAccumulatedAmount_CALCULATED { get; set; }
        public Nullable<int> ClientFirstValidReceipt_CALCULATED { get; set; }
        public decimal TotalValidReceipts_CALCULATED { get; set; }
        public decimal PendingReservedFunds_CALCULATED { get; set; }
        public decimal ClientCreditsRemaining_CALCULATED { get; set; }
        public decimal BalanceExternalAccounts_CALCULATED { get; set; }
        public string NotesPlainTextReadOnly { get; set; }
        public string DriverLicense { get; set; }
        public Nullable<decimal> ClientIncome_CALCULATED { get; set; }
        public Nullable<decimal> ClientBudget_CALCULATED { get; set; }
        public Nullable<int> DefaultCoAppID { get; set; }
        public string EffectiveCommunicationMethod_CALCULATED { get; set; }
        public Nullable<decimal> PSUserDefined1 { get; set; }
        public Nullable<decimal> PSUserDefined2 { get; set; }
        public Nullable<decimal> PSUserDefined3 { get; set; }
        public Nullable<decimal> PSUserDefined4 { get; set; }
        public Nullable<decimal> PSUserDefined5 { get; set; }
        public string ClosedBy { get; set; }
        public decimal NonDMPAmount_CALCULATED { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<int> ClientLastValidReceipt_CALCULATED { get; set; }
        public string EnteredByWebUserName { get; set; }
        public string HardshipLevel { get; set; }
        public string ClientType { get; set; }
        public string CompanyName { get; set; }
        public string WebSite { get; set; }
        public string CompanyType { get; set; }
        public decimal TotalNSFReceipts_CALCULATED { get; set; }
        public string AddressStatus { get; set; }
        public bool SkipNSFFee { get; set; }
        public bool IsBankrupt { get; set; }
        public Nullable<int> DMPDebtRangeID { get; set; }
        public string AddressMultiLine { get; set; }
        public Nullable<int> ImportDataLogID { get; set; }
        public byte Rating { get; set; }
        public Nullable<bool> IsMasterClient { get; set; }
        public Nullable<int> ClientIDGroup { get; set; }
        public Nullable<bool> Followup_CALCULATED { get; set; }
        public Nullable<System.DateTime> FollowupDate_CALCULATED { get; set; }
        public Nullable<System.DateTime> FirstContactDate_CALCULATED { get; set; }
        public string FirstContactUserID_CALCULATED { get; set; }
        public Nullable<System.DateTime> LastContactDate_CALCULATED { get; set; }
        public string LastContactUserID_CALCULATED { get; set; }
        public Nullable<short> CheckListItemsRequired_CALCULATED { get; set; }
        public string CallID { get; set; }
        public Nullable<decimal> LowestForecastedAccumulatedAmount_CALCULATED { get; set; }
        public string QBID { get; set; }
        public Nullable<int> ProcessingPolicyGroupID { get; set; }
        public string SSN_Masked { get; set; }
        public byte[] SSN_Encrypted { get; set; }
        public Nullable<int> LegalAssistantID { get; set; }
        public Nullable<int> ScoreModelID_CALCULATED { get; set; }
        public Nullable<decimal> ScoreModelValue_CALCULATED { get; set; }
        public Nullable<System.DateTime> ScoreModelLastDate_CALCULATED { get; set; }
        public Nullable<System.DateTime> MaxPromisedDate_CALCULATED { get; set; }
        public Nullable<int> ClientDistributionBatchID { get; set; }
        public Nullable<int> LastValidReceiptIDNSFdOrNot_CALCULATED { get; set; }
        public Nullable<bool> LastValidReceiptNSFd_CALCULATED { get; set; }
        public Nullable<System.DateTime> LastValidReceiptNSFDate_CALCULATED { get; set; }
        public Nullable<System.DateTime> LastValidReceiptDateReceived_CALCULATED { get; set; }
        public Nullable<int> LastValidReceiptNSFConsecutiveCount_CALCULATED { get; set; }
        public Nullable<bool> HomePhoneIsMobile { get; set; }
        public Nullable<bool> HomePhoneSMSEnabled { get; set; }
        public Nullable<bool> WorkPhoneIsMobile { get; set; }
        public Nullable<bool> WorkPhoneSMSEnabled { get; set; }
        public Nullable<bool> MobilePhoneIsMobile { get; set; }
        public Nullable<bool> MobilePhoneSMSEnabled { get; set; }
        public Nullable<int> HomePhoneCarrierID { get; set; }
        public Nullable<int> WorkPhoneCarrierID { get; set; }
        public Nullable<int> OtherPhoneCarrierID { get; set; }
        public Nullable<int> MobileCarrierID { get; set; }
        public bool PayPriorityOrderDesignatedByClient { get; set; }
        public Nullable<int> ContactScheduleID { get; set; }
        public Nullable<System.DateTime> FirstClearedReceiptDate_CALCULATED { get; set; }
        public string YodleeUserName { get; set; }
        public Nullable<int> YodleeStatus { get; set; }
        public Nullable<int> TimeToGMT_CALCULATED { get; set; }
        public int NextAccountOrdinal_CALCULATED { get; set; }
        public Nullable<int> MasterCreditorID { get; set; }
        public string IDType { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> InsuranceCompanyID { get; set; }
        public string CostCenter { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> PaymentTermID { get; set; }
        public string ClientRequirement_CALCULATED { get; set; }
        public Nullable<decimal> PSUserDefined6 { get; set; }
        public Nullable<decimal> PSUserDefined7 { get; set; }
        public Nullable<decimal> PSUserDefined8 { get; set; }
        public Nullable<decimal> PSUserDefined9 { get; set; }
        public Nullable<int> ClientIDGroupSecondary { get; set; }
        public bool UseCC { get; set; }
        public string SignNow_UserID { get; set; }
        public string SignNow_AccessToken { get; set; }
        public Nullable<int> MD_Qualifier { get; set; }
        public decimal ContractMonthlyFee { get; set; }
        public string MD_PolicyGroup { get; set; }
        public string MD_TypeInjuryQualifier { get; set; }
        public Nullable<System.DateTime> MD_DateOfInjury { get; set; }
        public bool CreditListed { get; set; }
        public Nullable<System.DateTime> CreditListedDate { get; set; }
        public Nullable<System.DateTime> CreditListedFirstDelinquencyDate { get; set; }
        public string MD_FamilyPlan { get; set; }
    
        public virtual ICollection<ACHBankAccounts> ACHBankAccounts { get; set; }
        public virtual ICollection<ACHBatch> ACHBatch { get; set; }
        public virtual ICollection<ACHBatchDetails> ACHBatchDetails { get; set; }
        public virtual ICollection<ClientCred> ClientCred { get; set; }
        public virtual ICollection<ClientCred> ClientCred1 { get; set; }
        public virtual ICollection<Clients> Clients1 { get; set; }
        public virtual Clients Clients2 { get; set; }
        public virtual Creditors Creditors { get; set; }
        public virtual CoApps CoApps { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual ICollection<CoApps> CoApps1 { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
