//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoApps
    {
        public CoApps()
        {
            this.ClientCred = new HashSet<ClientCred>();
            this.Clients = new HashSet<Clients>();
        }
    
        public int CoAppID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string CoAppFirst { get; set; }
        public string CoAppLast { get; set; }
        public string CoAppMiddleName { get; set; }
        public string CoAppSSN { get; set; }
        public Nullable<System.DateTime> CoAppDOB { get; set; }
        public Nullable<short> CoAppAge { get; set; }
        public string CoAppSex { get; set; }
        public string CoAppOccupation { get; set; }
        public string CoAppEmployer { get; set; }
        public Nullable<decimal> CoAppNetIncome { get; set; }
        public string CoAppHomePhone { get; set; }
        public string CoAppWorkPhone { get; set; }
        public string CoAppOtherPhone { get; set; }
        public string CoAppAddress1 { get; set; }
        public string CoAppAddress2 { get; set; }
        public string CoAppCity { get; set; }
        public string CoAppState { get; set; }
        public string CoAppZIP { get; set; }
        public string Relationship { get; set; }
        public string CoAppEmail { get; set; }
        public Nullable<int> CoAppMarital { get; set; }
        public Nullable<double> CoAppYearsAtJob { get; set; }
        public byte[] upsize_ts { get; set; }
        public string CoAppOccupationCategory { get; set; }
        public bool CoAppAddress1CommunicationPreferred { get; set; }
        public bool CoAppAddress1CommunicationDoNotUse { get; set; }
        public bool CoAppHomePhoneCommunicationPreferred { get; set; }
        public bool CoAppHomePhoneCommunicationDoNotUse { get; set; }
        public bool CoAppWorkPhoneCommunicationPreferred { get; set; }
        public bool CoAppWorkPhoneCommunicationDoNotUse { get; set; }
        public bool CoAppOtherPhoneCommunicationPreferred { get; set; }
        public bool CoAppOtherPhoneCommunicationDoNotUse { get; set; }
        public bool CoAppEmailCommunicationPreferred { get; set; }
        public bool CoAppEmailCommunicationDoNotUse { get; set; }
        public string CoAppHomePhoneStripped { get; set; }
        public string CoAppWorkPhoneStripped { get; set; }
        public string CoAppOtherPhoneStripped { get; set; }
        public Nullable<int> LeadID { get; set; }
        public string EnteredByWebUserName { get; set; }
        public bool CoAppEmployed { get; set; }
        public bool IsBillingContact { get; set; }
        public string CoAppFullName_CALCULATED { get; set; }
        public bool CoAppActive { get; set; }
        public string CoAppSSN_Masked { get; set; }
        public string Note { get; set; }
        public Nullable<bool> CoAppHomePhoneIsMobile { get; set; }
        public Nullable<bool> CoAppHomePhoneSMSEnabled { get; set; }
        public Nullable<bool> CoAppWorkPhoneIsMobile { get; set; }
        public Nullable<bool> CoAppWorkPhoneSMSEnabled { get; set; }
        public Nullable<bool> CoAppOtherPhoneIsMobile { get; set; }
        public Nullable<bool> CoAppOtherPhoneSMSEnabled { get; set; }
        public string CoAppHomePhoneType { get; set; }
        public string CoAppWorkPhoneType { get; set; }
        public string CoAppOtherPhoneType { get; set; }
        public Nullable<int> CoAppHomePhoneCarrierID { get; set; }
        public Nullable<int> CoAppWorkPhoneCarrierID { get; set; }
        public Nullable<int> CoAppOtherPhoneCarrierID { get; set; }
        public bool CoAppUserDefined1 { get; set; }
        public Nullable<int> CoAppOccupationCategoryID { get; set; }
        public bool IsBankrupt { get; set; }
        public string BankruptcyAttorneyPhoneNumber { get; set; }
        public Nullable<System.DateTime> BankruptcyFilingDate { get; set; }
        public Nullable<System.DateTime> BankruptcyHearingDate { get; set; }
        public string BankruptcyTrusteeLastName { get; set; }
        public string BankruptcyTrusteeFirstName { get; set; }
        public string BankruptcyTrusteeMiddleName { get; set; }
        public string BankruptcyTrusteeAddress1 { get; set; }
        public string BankruptcyTrusteeAddress2 { get; set; }
        public string BankruptcyTrusteeCity { get; set; }
        public string BankruptcyTrusteeState { get; set; }
        public string BankruptcyTrusteeZip { get; set; }
        public string BankruptcyTrusteePhoneNumber { get; set; }
        public string BankruptcyAttorneyAddress1 { get; set; }
        public string BankruptcyAttorneyAddress2 { get; set; }
        public string BankruptcyAttorneyCity { get; set; }
        public string BankruptcyAttorneyState { get; set; }
        public string BankruptcyAttorneyZip { get; set; }
        public string BankruptcyCourtCode { get; set; }
        public string BankruptcyCourtAddress1 { get; set; }
        public string BankruptcyCourtAddress2 { get; set; }
        public string BankruptcyCourtCity { get; set; }
        public string BankruptcyCourtState { get; set; }
        public string BankruptcyCourtZip { get; set; }
        public string BankruptcyCourtPostalAddress1 { get; set; }
        public string BankruptcyCourtPostalAddress2 { get; set; }
        public string BankruptcyCourtPostalCity { get; set; }
        public string BankruptcyCourtPostalState { get; set; }
        public string BankruptcyCourtPostalZip { get; set; }
        public bool BankruptcyProofOfClaimIssued { get; set; }
        public Nullable<System.DateTime> BankruptcyProofOfClaimResponseDate { get; set; }
        public Nullable<System.DateTime> BankruptcyProofOfClaimFiledDate { get; set; }
        public Nullable<decimal> BankruptcyProofOfClaimAmount { get; set; }
        public bool BankruptcyDismissed { get; set; }
        public Nullable<System.DateTime> BankruptcyDismissedDate { get; set; }
        public bool BankruptcyDischarged { get; set; }
        public Nullable<System.DateTime> BankruptcyDischargedDate { get; set; }
        public string BankruptcyChapter { get; set; }
        public string BankruptcyAttorneyLastName { get; set; }
        public string BankruptcyAttorneyFirstName { get; set; }
        public string BankruptcyAttorneyMiddleName { get; set; }
        public string BankruptcyCourtDistrictCode { get; set; }
        public string BankruptcyCaseNumber { get; set; }
        public string SignNow_UserID { get; set; }
        public string SignNow_AccessToken { get; set; }
        public string MD_PolicyGroup { get; set; }
    
        public virtual ICollection<ClientCred> ClientCred { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
    }
}
