//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string CreditsoftDatabase { get; set; }
        public string SecurityGroup { get; set; }
        public int MenuOption { get; set; }
        public bool Active { get; set; }
    }
}
