//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditors
    {
        public Creditors()
        {
            this.ACHBatch = new HashSet<ACHBatch>();
            this.Checks = new HashSet<Checks>();
            this.ClientCred = new HashSet<ClientCred>();
            this.Clients = new HashSet<Clients>();
            this.Payments = new HashSet<Payments>();
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int CreditorID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Telephone { get; set; }
        public string AltTelephone { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<decimal> FairShare { get; set; }
        public string BillingPeriod { get; set; }
        public Nullable<System.DateTime> LastInvoicePrinted { get; set; }
        public bool Deduct { get; set; }
        public bool Bill { get; set; }
        public string Terms { get; set; }
        public string GuideLines { get; set; }
        public Nullable<decimal> ProposalPct { get; set; }
        public string PName { get; set; }
        public string PAddress1 { get; set; }
        public string PAddress2 { get; set; }
        public string PCity { get; set; }
        public string PState { get; set; }
        public string PZIP { get; set; }
        public string PAttn { get; set; }
        public string PPhone { get; set; }
        public string PFax { get; set; }
        public string BName { get; set; }
        public string BAddress1 { get; set; }
        public string BAddress2 { get; set; }
        public string BCity { get; set; }
        public string BState { get; set; }
        public string BZIP { get; set; }
        public string BAttn { get; set; }
        public string BPhone { get; set; }
        public string BFax { get; set; }
        public string Notes { get; set; }
        public bool Consolidate { get; set; }
        public bool Alert { get; set; }
        public Nullable<decimal> APR { get; set; }
        public string Codes { get; set; }
        public bool ShowOnLetters { get; set; }
        public Nullable<System.DateTime> EditableUntil { get; set; }
        public string CreditorType { get; set; }
        public bool Commissionable { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ClientIDcopy { get; set; }
        public Nullable<decimal> MinimumPercent { get; set; }
        public int PercentOf { get; set; }
        public Nullable<decimal> MinimumAmount { get; set; }
        public Nullable<int> NewCreditorID { get; set; }
        public string BillerID { get; set; }
        public int DefBankAccountID { get; set; }
        public string BillerType { get; set; }
        public string ReversalBillerID { get; set; }
        public string ReversalAccountNumber { get; set; }
        public bool TempCreditor { get; set; }
        public string OperatorStamp { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public byte[] upsize_ts { get; set; }
        public bool Generic { get; set; }
        public Nullable<bool> ReduceInterest { get; set; }
        public Nullable<bool> EliminateInterest { get; set; }
        public Nullable<bool> ReAge { get; set; }
        public Nullable<short> ReAgeAfter { get; set; }
        public Nullable<bool> DropLateFees { get; set; }
        public Nullable<System.DateTime> FirstInvoiceDate { get; set; }
        public Nullable<decimal> APROutsideCC { get; set; }
        public bool UseForEnrollment { get; set; }
        public string PContact { get; set; }
        public string BContact { get; set; }
        public bool ValidateMasks { get; set; }
        public Nullable<double> ReducePoints { get; set; }
        public bool UseRPPSProposals { get; set; }
        public string RPPSBillerIDOverride { get; set; }
        public Nullable<int> PerCheck { get; set; }
        public Nullable<int> PerBill { get; set; }
        public Nullable<bool> Guaranteed { get; set; }
        public Nullable<int> Profile { get; set; }
        public string UserDefined1 { get; set; }
        public string UserDefined2 { get; set; }
        public bool FullBudgetDisclosure { get; set; }
        public bool FullBudgetCreditors { get; set; }
        public Nullable<System.DateTime> CreditorAdded { get; set; }
        public string UserDefinedCode { get; set; }
        public Nullable<decimal> OverrideMinimumInvoiceAmount { get; set; }
        public bool UseForInternet { get; set; }
        public string BPName { get; set; }
        public string BPAddress1 { get; set; }
        public string BPAddress2 { get; set; }
        public string BPCity { get; set; }
        public string BPState { get; set; }
        public string BPZip { get; set; }
        public string BPAttn { get; set; }
        public string BPPhone { get; set; }
        public string BPFax { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public bool SkipBulkProposals { get; set; }
        public bool SkipImportMask { get; set; }
        public string Password { get; set; }
        public string QBID { get; set; }
        public string EditSequence { get; set; }
        public Nullable<decimal> PADMinimum { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> DefaultSettlementPercentage { get; set; }
        public bool ContributeInFS { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> MaximumFairShareAmount { get; set; }
        public bool RequireStubWithInvoice { get; set; }
        public string BankRoutingNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankCity { get; set; }
        public string BankState { get; set; }
        public string BankZipCode { get; set; }
        public Nullable<bool> OverridePayOffBehavior { get; set; }
        public string DefaultCreditorPaymentType { get; set; }
        public bool AllowPreBankruptcy { get; set; }
        public bool AllowLessThanFull { get; set; }
        public bool UsePhonePay { get; set; }
        public string TelephoneStripped { get; set; }
        public string AltTelephoneStripped { get; set; }
        public string FaxStripped { get; set; }
        public string BPhoneStripped { get; set; }
        public string PPhoneStripped { get; set; }
        public string BFaxStripped { get; set; }
        public string PFaxStripped { get; set; }
        public string BPPhoneStripped { get; set; }
        public string BPFaxStripped { get; set; }
        public string BankAddress { get; set; }
        public string AddedBy { get; set; }
        public string LoggedUserID { get; set; }
        public Nullable<System.DateTime> LoggedOn { get; set; }
        public Nullable<short> DropLateFeesAfter { get; set; }
        public Nullable<bool> DropOverlimitFees { get; set; }
        public Nullable<short> DropOverlimitFeesAfter { get; set; }
        public Nullable<int> CreditorGroupCreditorID { get; set; }
        public string OtherFeesNotes { get; set; }
        public string ReageFrequency { get; set; }
        public Nullable<bool> AllowRebates { get; set; }
        public string RebatesNotes { get; set; }
        public string DropPolicyNotes { get; set; }
        public string InterestRangeNotes { get; set; }
        public Nullable<short> MaxMonthsToPayout { get; set; }
        public Nullable<bool> CreditorGroupIsParent { get; set; }
        public bool AutoResendProposals { get; set; }
        public bool DefaultHoldProposals { get; set; }
        public bool DefaultHoldProposalUntilFirstReceipt { get; set; }
        public Nullable<decimal> RebatesPct { get; set; }
        public Nullable<short> EmailStatus { get; set; }
        public string CompoundFrequency { get; set; }
        public bool SendProposalsByFax { get; set; }
        public bool AllowFeeOverCalculatedDefault { get; set; }
        public string NotesPlainTextReadOnly { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<int> HoldProposalsDaysBeforeNextDisbursement { get; set; }
        public bool EnableMod10Validation { get; set; }
        public Nullable<decimal> MinimumPercentBeforeDMP { get; set; }
        public Nullable<int> PercentOfBeforeDMP { get; set; }
        public Nullable<decimal> MinimumAmountBeforeDMP { get; set; }
        public string UserDefined3 { get; set; }
        public bool AllowCDV { get; set; }
        public Nullable<int> ContactScheduleID { get; set; }
        public bool AllowCDD { get; set; }
        public Nullable<decimal> GCSPayeeID { get; set; }
        public Nullable<decimal> GCSPayeeAddressID { get; set; }
        public Nullable<decimal> GCSPayeeContactID { get; set; }
        public Nullable<decimal> GCSPayeeBankID { get; set; }
        public bool AllowCDN { get; set; }
        public bool ReturnCDR { get; set; }
        public bool ReturnCDT { get; set; }
        public bool ReturnCDA { get; set; }
        public bool ReturnCDV { get; set; }
        public bool ReturnCDC { get; set; }
        public bool ReturnCDM { get; set; }
        public bool AllowCDF { get; set; }
        public bool DefaultDNDUntilProposalAccepted { get; set; }
        public bool AllowCallToAction { get; set; }
        public bool AllowHardship { get; set; }
        public Nullable<int> CollectionPlanID { get; set; }
        public Nullable<decimal> InternalFeePercentage { get; set; }
        public Nullable<decimal> ExternalFeePercentage { get; set; }
        public Nullable<decimal> ExternalFeePercentageGuaranteed { get; set; }
        public Nullable<decimal> MaximumFeeAmount { get; set; }
        public bool AllowReversalOfFeesOnRefunds { get; set; }
        public bool HideBalance { get; set; }
        public string CreditorStatus { get; set; }
        public string AddedByWebUserName { get; set; }
        public string PortfolioType { get; set; }
        public bool ReportToCreditBureaus { get; set; }
        public string DefaultDebtType { get; set; }
        public Nullable<int> SalesForceID { get; set; }
        public bool ProposalRequiresCDN { get; set; }
        public Nullable<decimal> GCSDirectPayeeID { get; set; }
        public string BankAccountNumber_Masked { get; set; }
        public string BACSReferenceNumber { get; set; }
        public string BACSSortCode { get; set; }
        public string ResubmissionBillerID_Override { get; set; }
        public string UserDefined4 { get; set; }
        public string UserDefined5 { get; set; }
        public string UserDefined6 { get; set; }
        public string UserDefined7 { get; set; }
        public Nullable<int> HoldProposalsDaysFromQueuing { get; set; }
        public bool HoldProposalsBasedOnIncomeVariance { get; set; }
        public string M2_CardHolderID_BIN7 { get; set; }
        public bool M2_BankInfo_LinkedTo_BIN7 { get; set; }
        public bool M2_BankInfo_NeedsUpdate { get; set; }
        public string M2_CardHolderID_BIN2 { get; set; }
        public Nullable<int> SQLFormulaID { get; set; }
        public Nullable<int> ReducedAPRSQLFormulaID { get; set; }
        public bool UseReducedAPRFormula { get; set; }
        public bool UseDefMonthlyPaymentFormula { get; set; }
        public Nullable<int> DefaultLoanTerm { get; set; }
        public int M2_BIN2_Counter_CALCULATED { get; set; }
        public string CreditorRequirement_CALCULATED { get; set; }
        public bool PhoneCommunicationDoNotUse { get; set; }
        public bool AltPhoneCommunicationDoNotUse { get; set; }
        public bool PhoneCommunicationPreferred { get; set; }
        public bool AltPhoneCommunicationPreferred { get; set; }
        public bool PPhoneCommunicationDoNotUse { get; set; }
        public bool BPhoneCommunicationDoNotUse { get; set; }
        public bool PPhoneCommunicationPreferred { get; set; }
        public bool BPhoneCommunicationPreferred { get; set; }
        public string Product { get; set; }
        public Nullable<int> DefBillPayBankAccountID { get; set; }
        public string BillPayBillerID { get; set; }
        public Nullable<int> YodleeDefaultContentServiceID { get; set; }
        public bool PopularBillPayPayee { get; set; }
        public string IPayout_CheckProfileID { get; set; }
        public string IPayout_WireProfileID { get; set; }
        public string IPayout_PhonePayProfileID { get; set; }
        public bool PaymentProcessor_NeedsUpdate { get; set; }
        public string IPayout_UserName { get; set; }
        public bool SkipFairShareForNonAcceptedAccounts { get; set; }
        public string EIN_SSN { get; set; }
        public string EIN_SSN_Masked { get; set; }
        public string IDType { get; set; }
        public bool AllowCSPTier1 { get; set; }
        public bool AllowCSPTier2 { get; set; }
        public bool AllowCSPTier3 { get; set; }
    
        public virtual ICollection<ACHBatch> ACHBatch { get; set; }
        public virtual BankAccounts BankAccounts { get; set; }
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual ICollection<ClientCred> ClientCred { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Creditors Creditors1 { get; set; }
        public virtual Creditors Creditors2 { get; set; }
        public virtual Creditors Creditors11 { get; set; }
        public virtual Creditors Creditors3 { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
