//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyStatements.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACHBankAccounts> ACHBankAccounts { get; set; }
        public virtual DbSet<ACHBatch> ACHBatch { get; set; }
        public virtual DbSet<ACHBatchDetails> ACHBatchDetails { get; set; }
        public virtual DbSet<ACHBatchGroup> ACHBatchGroup { get; set; }
        public virtual DbSet<ACHGroups> ACHGroups { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankAccounts> BankAccounts { get; set; }
        public virtual DbSet<CheckRun> CheckRun { get; set; }
        public virtual DbSet<Checks> Checks { get; set; }
        public virtual DbSet<ClientCred> ClientCred { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<CoApps> CoApps { get; set; }
        public virtual DbSet<Creditors> Creditors { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<Custom_DailyStatements> Custom_DailyStatements { get; set; }
    }
}
