//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPStatements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public int CheckID { get; set; }
        public int BankAccountID { get; set; }
        public int CreditorID { get; set; }
        public int ClientID { get; set; }
        public bool NCI { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<int> PaymentIDCopy { get; set; }
        public bool Refunded { get; set; }
        public Nullable<bool> Resubmitted { get; set; }
        public Nullable<long> BatchID { get; set; }
        public Nullable<int> ClientCredID { get; set; }
        public Nullable<int> RefundDetailID { get; set; }
        public Nullable<int> ProgramScheduleDebtorID { get; set; }
        public Nullable<int> CommissionBatchID { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<int> FSPaymentID { get; set; }
        public string TraceNumber { get; set; }
        public Nullable<int> SettlementScheduleID { get; set; }
        public Nullable<int> ReversedCommissionBatchID { get; set; }
        public Nullable<int> PaymentCheckRunID { get; set; }
        public Nullable<int> FSClientCredID { get; set; }
        public bool NonCommissionable { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string AccountNumber_Masked { get; set; }
        public Nullable<decimal> GCSPaymentID { get; set; }
        public Nullable<decimal> GCSDebitID { get; set; }
        public Nullable<decimal> PrincipalAmount { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public bool GeneratedByCollectionPlan { get; set; }
        public string M2_TransactionID_Step1 { get; set; }
        public string M2_TransactionID_Step2 { get; set; }
        public short M2_TransComplete { get; set; }
        public string ClientState { get; set; }
        public string PaymentProcessor_TransactionRefID { get; set; }
        public Nullable<int> TransferBalanceBatchDetailID { get; set; }
        public string Counselor { get; set; }
        public string PaymentProcessor_CreditorProfileID { get; set; }
        public string PaymentProcessor_CreditorProfileType { get; set; }
        public Nullable<int> CreditorGroupCreditorID { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Creditors Creditors { get; set; }
    }
}
